const theme = {
    font: "Catamaran, 'Helvetica Neue', Helvetica, Arial, sans-serif",
    breakpoints: {
        mobile: '320px',
        tablet: '768px',
        desktop: '1024px',
        desktop_large: '1280px',
    },
    colors: {
        header_primary: '#fff',
        header_secondary: '#b9bbbe',
        text_normal: '#dcddde',
        text_muted: '#a3a6aa',
        text_link: 'hsl(197, 100%, 47.8%)',
        text_link_low_saturation: 'hsl(197, 100%, 52.9%)',
        text_positive: 'hsl(139, 51.6%, 52.2%)',
        text_warning: 'hsl(38, 95.7%, 54.1%)',
        text_danger: 'hsl(359, 82%, 73.9%)',
        text_brand: 'hsl(235, 86.1%, 77.5%)',
        background_primary: '#36393f',
        background_secondary: '#2f3136',
        background_timestamp: 'rgba(79,84,92,0.48)',
        text_input_border: '#040405',
        text_input_placeholder: '#707277',
        text_input_color: '#f6f6f7',
        primary: '#5468ff',
        button_danger_background: 'hsl(359, 66.7%, 54.1%)',
        button_danger_background_hover: 'hsl(359, 56.3%, 40.4%)',
        button_danger_background_active: 'hsl(359, 56.4%, 35.1%)',
        button_danger_background_disabled: 'hsl(359, 66.7%, 54.1%)',
        button_positive_background: 'hsl(139, 47.1%, 33.3%)',
        button_positive_background_hover: 'hsl(138, 46.8%, 24.3%)',
        button_positive_background_active: 'hsl(138, 46.9%, 22.2%)',
        button_positive_background_disabled: 'hsl(139, 47.1%, 33.3%)',
        button_secondary_background: '#4f545c',
        button_secondary_background_hover: '#686d73',
        button_secondary_background_active: '#72767d',
        button_secondary_background_disabled: '#4f545c',
        button_outline_danger_text: '#fff',
        button_outline_danger_border: 'hsl(359, 82.6%, 59.4%)',
        button_outline_danger_background: 'hsla(0, 0%, 100%, 0)',
        button_outline_danger_background_hover: 'hsl(359, 66.7%, 54.1%)',
        button_outline_danger_text_hover: '#fff',
        button_outline_danger_border_hover: 'hsl(359, 66.7%, 54.1%)',
        button_outline_danger_background_active: 'hsl(359, 56.7%, 48%)',
        button_outline_danger_text_active: '#fff',
        button_outline_danger_border_active: 'hsl(359, 66.7%, 54.1%)',
        button_outline_positive_text: '#fff',
        button_outline_positive_border: 'hsl(139, 47.3%, 43.9%)',
        button_outline_positive_background: 'hsla(0, 0%, 100%, 0)',
        button_outline_positive_background_hover: 'hsl(139, 47.1%, 33.3%)',
        button_outline_positive_text_hover: '#fff',
        button_outline_positive_border_hover: 'hsl(139, 47.1%, 33.3%)',
        button_outline_positive_background_active: 'hsl(138, 46.8%, 24.3%)',
        button_outline_positive_text_active: '#fff',
        button_outline_positive_border_active: 'hsl(138, 46.8%, 24.3%)',
        button_outline_brand_text: '#fff',
        button_outline_brand_border: 'hsl(235, 85.6%, 64.7%)',
        button_outline_brand_background: 'hsla(0, 0%, 100%, 0)',
        button_outline_brand_background_hover: 'hsl(235, 85.6%, 64.7%)',
        button_outline_brand_text_hover: '#fff',
        button_outline_brand_border_hover: 'hsl(235, 85.6%, 64.7%)',
        button_outline_brand_background_active: 'hsl(235, 51.4%, 52.4%)',
        button_outline_brand_text_active: '#fff',
        button_outline_brand_border_active: 'hsl(235, 51.4%, 52.4%)',
        button_outline_primary_text: '#fff',
        button_outline_primary_border: '#4f545c',
        button_outline_primary_background: 'hsla(0, 0%, 100%, 0)',
        button_outline_primary_background_hover: '#4f545c',
        button_outline_primary_text_hover: '#fff',
        button_outline_primary_border_hover: '#4f545c',
        button_outline_primary_background_active: '#686d73',
        button_outline_primary_text_active: '#fff',
        button_outline_primary_border_active: '#686d73',
    },
}

export default theme
